name: elrond_gateway
description: Elrond gateway
version: 1.0.0


environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  dio: ^4.0.6
  json_annotation: ^4.5.0
  meta: ^1.8.0
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.16.0
  retrofit_generator: ^4.0.1
