name: elrond_gateway
description: Elrond gateway
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  http: ^0.13.4
  json_annotation: ^4.5.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  lints: ^2.0.0
  mockito: ^5.2.0
  test: ^1.16.0
